### ISSUE TITLE
Create missing directories

### ISSUE THREAD

**Issue by tpankaj** [bddmodelcar/training#28]
When freshly pulled, the code often crashes because it expects save/logs/other directories to exist. This is not a necessary error. Instead of crashing, create the directories if they don't exist.

**Comment by raunakdoesdev** [comment]
Rather than this, I think a better idea would be to add a README.md to these folders that don't exist, that way the folders will be created when pulled, the code will be less cluttered, and the usage of those folders can be documented in the READMEs. I've already done this for logs and save, can you tell me what other folders are causing problems?

**Comment by tpankaj** [comment]
Yes, that's a good idea. Let me get back to you on that.
